name: Build Docker image and deploy to Northflank

on:
  workflow_dispatch:

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/F1-ML-Prediction       

      - name: Build Docker image
        run: docker build . --file Dockerfile --no-cache --tag ${{ steps.meta.outputs.tags }}

      - name: Push Docker image
        run: docker push ${{ steps.meta.outputs.tags }}

      - name: Deploy to Northflank
        uses: northflank/deploy-to-northflank@v1
        with:
          northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
          project-id: ${{ secrets.PROJECT_ID }}
          service-id: ${{ secrets.SERVICE_ID }}
          image-path: ${{ steps.meta.outputs.tags }}