name: Python application test

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make setup
  
    - name: Run tests
      run: make tests
    
    - name: Update driver standings data
      run: python src/import_data.py

    - name: Commit and Push if it changed
      run: |
        git config --global user.email "github.action@github"
        git config --global user.name "Github Action"
        git add -A
        git commit -m "Update driver standings data" -a || exit 0
        git push
