name: Python Tests

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'src/*.py'
  workflow_dispatch:  # Allows manual triggering to test the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{secrets.GH_TOKEN}}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make setup
  
    - name: Run tests
      run: make tests
