name: Python application test

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make setup
  
    - name: Run tests
      run: make tests
    
    - name: Update driver standings data
      run: make import_data

    - name: Commit and Push if it changed
      run: |
        git config --local user.email "louis.arbey@efrei.net"
        git config --local user.name "GitHub Action"
        git add.
        git diff-index --quiet HEAD || git commit -m "Update driver standings data"
        git push origin master
