name: Training and saving of the Model

on:
  push:
    branches:
      - master
    paths:
      - 'data/api_ergast/*'
  workflow_dispatch:  # Allows manual triggering to test the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GH_TOKEN}}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make setup
  
    - name: Train and save the model
      run: make train_and_save_model
    
    - name: Commit and Push if it changed
      run: |
        git config --global user.email "github.action@github"
        git config --global user.name "Github Action"
        git add -A
        git commit -m "Trained and saved the New model" -a || exit 0
        git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:master